# Generated by Django 2.1.2 on 2018-10-21 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zibcrm', '0003_auto_20181022_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zibcrm.Store'),
        ),
    ]
