# Generated by Django 2.1.2 on 2018-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zibcrm', '0008_auto_20181023_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='felez_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'طلا'), (2, 'پلاتین'), (3, 'نقره')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='felez_weight',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='stone_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Brillianum'), (2, 'Emerald'), (3, 'Ruby Ruby'), (4, 'Sapphire'), (5, 'Ruby Quilted'), (6, 'Amethyst'), (7, 'Thyroid'), (8, 'Pearl'), (9, 'Colored Stone'), (10, 'Seeds'), (11, 'GIA or HRD Seeds'), (12, 'Firoozeh'), (13, 'Topaz'), (14, 'Tanzanite'), (15, 'Opal'), (16, 'Tourmaline')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='stone_weight',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
