# Generated by Django 2.1.2 on 2018-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zibcrm', '0011_auto_20181023_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='felez_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(),
        ),
    ]
